
main1:
	gcc -pthread main1.c -o main1

main2:
	gcc -pthread main2.c -o main2

main3:
	gcc -pthread main3.c -o main3

main4:
	gcc -pthread main4.c -o main4

client:
	gcc -pthread client.c -o client

attacker:
	gcc -pthread attacker.c -o attacker -lm

clean:
	rm main1 main2 main3 main4
