
GCC= gcc -o3 -pthread

main1:
	${GCC} main1.c -o main1

main2:
	${GCC} main2.c -o main2

main3:
	${GCC} main3.c -o main3

main4:
	${GCC} main4.c -o main4

client:
	${GCC} client.c -o client

attacker:
	${GCC} attacker.c -o attacker -lm

clean:
	rm main1 main2 main3 main4
